// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwkjbiixjhdlvdzxszkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3a2piaWl4amhkbHZkenhzemtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2OTMxMDMsImV4cCI6MjA1MjI2OTEwM30.JrxCtQQzLK2pNs0VmQFN7SifgmqAunUVF_mL-2aZaFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);